name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
          cache: true

      - name: Derive version info
        id: meta
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ steps.meta.outputs.tag }}
          LDFLAGS: -s -w -X github.com/isaaclins/LazyLab/cmd.Version=${{ steps.meta.outputs.tag }} -X github.com/isaaclins/LazyLab/cmd.Commit=${{ steps.meta.outputs.commit }} -X github.com/isaaclins/LazyLab/cmd.Date=${{ steps.meta.outputs.date }}
        run: |
          chmod +x ./build.sh
          ./build.sh
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          OUT="lazylab-${{ steps.meta.outputs.tag }}-${{ matrix.goos }}-${{ matrix.goarch }}$EXT"
          mv bin/lazylab$EXT "$OUT"
          shasum -a 256 "$OUT" > "$OUT.sha256"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lazylab-${{ steps.meta.outputs.tag }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            lazylab-${{ steps.meta.outputs.tag }}-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/**/lazylab-*
